### ISSUE TITLE
List of GitHub public projects that use hakiri, and a way to retrieve hakiri reports for those projects

### ISSUE THREAD

**Issue by nasifimtiazohi** [hakirisec/hakiri_toolbelt#16]
Is there any list of GitHub public projects that use hakiri? 

Can such a list be made public? Given that, the list would include only public projects, I don't think there's any privacy issue.

Also, on a further note, is there any way to easily access all the hakiri reports for a given GitHub public project? For example, for project X, I want all the individual reports that hakiri generates running on every commit/PR. I believe (from googling) hakiri doesn't have an API like some other tools (travisci). Is there any other way one can easily/systematically access that data?

Thanks,
Nasif

**Comment by vasinov** [comment]
@nasifimtiazohi 
> Is there any list of GitHub public projects that use hakiri?

here's the list of all public Hakiri projects: https://hakiri.io/security-watch

> Is there any other way one can easily/systematically access that data?

Hakiri doesn't have an API for reports, only a web UI.
