### ISSUE TITLE
Depend on json instead of json_pure

### ISSUE THREAD

**Issue by qerub** [hakirisec/hakiri_toolbelt#5]
…unless there's a good reason for the current dependency.

**Comment by vasinov** [comment]
@qerub I had some issues with the json gem in Ruby 1.8.x. I am going to drop support for old Ruby very soon, so json_pure will be replaced with json. I will close this issue once it's done.

Thanks for reporting it!

**Comment by vasinov** [comment]
@qerub now Hakiri relies on the json gem instead of json_pure.
